version: '3.3'
services:
    database:
        image: 'mongo'
        container_name: 'mongodb'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        ports:
            - 27017:27017
            - 27018:27018
            - 27019:27019
